"""replace budget targets with budget plans

Monthly targets become quarterly plans (F-BUD-7): one per quarter in which a target was in
force, up to the current quarter, with the targets in force in its first month. A change of
target within a quarter closes the plan early and starts a replacement plan, so every month
keeps the target it had. The downgrade rebuilds the monthly targets from the plans.

Revision ID: e1f2a3b4c5d6
Revises: 1cdee9503c79
Create Date: 2026-10-10 11:58:10.257421
"""

from collections import defaultdict
from collections.abc import Sequence
from datetime import UTC, date, datetime
from decimal import Decimal
from typing import Any

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e1f2a3b4c5d6"
down_revision: str | None = "1cdee9503c79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_plan",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("start_month", sa.Date(), nullable=False),
        sa.Column("end_month", sa.Date(), nullable=False),
        sa.Column("expected_income", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("close_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('year', 'semester', 'quarter')", name=op.f("ck_budget_plan_kind")
        ),
        sa.CheckConstraint(
            "expected_income IS NULL OR expected_income >= 0",
            name=op.f("ck_budget_plan_income_not_negative"),
        ),
        sa.CheckConstraint(
            "extract(day from start_month) = 1 AND extract(day from end_month) = 1",
            name=op.f("ck_budget_plan_months_first_day"),
        ),
        sa.CheckConstraint(
            "start_month <= end_month", name=op.f("ck_budget_plan_start_before_end")
        ),
        sa.ForeignKeyConstraint(
            ["household_id"], ["household.id"], name=op.f("fk_budget_plan_household_id_household")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_plan")),
    )
    op.create_index(
        op.f("ix_budget_plan_household_id"), "budget_plan", ["household_id"], unique=False
    )
    op.create_table(
        "budget_plan_target",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_budget_plan_target_amount_not_negative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_budget_plan_target_category_id_category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["budget_plan.id"],
            name=op.f("fk_budget_plan_target_plan_id_budget_plan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_plan_target")),
        sa.UniqueConstraint(
            "plan_id", "category_id", name=op.f("uq_budget_plan_target_plan_id_category_id")
        ),
    )
    _targets_to_plans()
    op.drop_index(op.f("ix_budget_target_household_id"), table_name="budget_target")
    op.drop_table("budget_target")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budget_target",
        sa.Column("household_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("valid_from", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint(
            "EXTRACT(day FROM valid_from) = 1::numeric",
            name=op.f("ck_budget_target_valid_from_first_of_month"),
        ),
        sa.CheckConstraint(
            "amount IS NULL OR amount >= 0::numeric",
            name=op.f("ck_budget_target_amount_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_budget_target_category_id_category"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"], ["household.id"], name=op.f("fk_budget_target_household_id_household")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_budget_target")),
        sa.UniqueConstraint(
            "category_id",
            "valid_from",
            name=op.f("uq_budget_target_category_id_valid_from"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_budget_target_household_id"), "budget_target", ["household_id"], unique=False
    )
    _plans_to_targets()
    op.drop_table("budget_plan_target")
    op.drop_index(op.f("ix_budget_plan_household_id"), table_name="budget_plan")
    op.drop_table("budget_plan")
    # ### end Alembic commands ###


# Months as integers (year * 12 + month - 1), so ranges are plain arithmetic.


def _index(day: date) -> int:
    return day.year * 12 + day.month - 1


def _day(index: int) -> date:
    return date(index // 12, index % 12 + 1, 1)


def _targets_to_plans() -> None:
    conn = op.get_bind()
    rows = conn.execute(
        sa.text("SELECT household_id, category_id, valid_from, amount FROM budget_target")
    ).all()
    by_household: dict[Any, dict[Any, list[tuple[int, Decimal | None]]]] = defaultdict(
        lambda: defaultdict(list)
    )
    for household, category, valid_from, amount in rows:
        by_household[household][category].append((_index(valid_from), amount))
    today = _index(datetime.now(UTC).date())
    for household, history in by_household.items():
        changes = sorted({start for entries in history.values() for start, _ in entries})
        first_quarter = changes[0] - changes[0] % 3
        last = max(changes[-1], today)
        for quarter_start in range(first_quarter, last - last % 3 + 1, 3):
            quarter_end = quarter_start + 2
            cuts = [quarter_start, *(c for c in changes if quarter_start < c <= quarter_end)]
            for i, start in enumerate(cuts):
                end = cuts[i + 1] - 1 if i + 1 < len(cuts) else quarter_end
                in_force = {
                    category: amount
                    for category, entries in history.items()
                    if (amount := _in_force(entries, start)) is not None
                }
                if in_force:
                    _insert_plan(conn, household, start, end, in_force)


def _in_force(entries: list[tuple[int, Decimal | None]], month: int) -> Decimal | None:
    started = [(start, amount) for start, amount in entries if start <= month]
    return max(started, key=lambda e: e[0])[1] if started else None


def _insert_plan(
    conn: Any, household: Any, start: int, end: int, targets: dict[Any, Decimal]
) -> None:
    plan = conn.scalar(
        sa.text(
            "INSERT INTO budget_plan (id, household_id, kind, year, number, start_month, end_month)"
            " VALUES (gen_random_uuid(), :h, 'quarter', :y, :n, :s, :e) RETURNING id"
        ),
        {
            "h": household,
            "y": start // 12,
            "n": start % 12 // 3 + 1,
            "s": _day(start),
            "e": _day(end),
        },
    )
    for category, amount in targets.items():
        conn.execute(
            sa.text(
                "INSERT INTO budget_plan_target (id, plan_id, category_id, amount)"
                " VALUES (gen_random_uuid(), :p, :c, :a)"
            ),
            {"p": plan, "c": category, "a": amount},
        )


def _plans_to_targets() -> None:
    """Each plan's targets from its first month; none between plans. The last plan's targets
    stay in force, as monthly targets did before plans."""
    conn = op.get_bind()
    plans = conn.execute(
        sa.text(
            "SELECT id, household_id, start_month, end_month FROM budget_plan ORDER BY start_month"
        )
    ).all()
    amounts: dict[Any, dict[Any, Decimal]] = defaultdict(dict)
    for plan, category, amount in conn.execute(
        sa.text("SELECT plan_id, category_id, amount FROM budget_plan_target")
    ):
        amounts[plan][category] = amount
    by_household: dict[Any, list[Any]] = defaultdict(list)
    for plan in plans:
        by_household[plan.household_id].append(plan)
    for household, household_plans in by_household.items():
        categories = {c for p in household_plans for c in amounts[p.id]}
        current: dict[Any, Decimal | None] = dict.fromkeys(categories)
        for i, plan in enumerate(household_plans):
            for category in categories:
                _change(
                    conn,
                    household,
                    category,
                    plan.start_month,
                    current,
                    amounts[plan.id].get(category),
                )
            following = household_plans[i + 1] if i + 1 < len(household_plans) else None
            after = _day(_index(plan.end_month) + 1)
            if following is not None and following.start_month != after:
                for category in categories:
                    _change(conn, household, category, after, current, None)


def _change(
    conn: Any,
    household: Any,
    category: Any,
    month: date,
    current: dict[Any, Decimal | None],
    amount: Decimal | None,
) -> None:
    if current[category] == amount:
        return
    current[category] = amount
    conn.execute(
        sa.text(
            "INSERT INTO budget_target (id, household_id, category_id, valid_from, amount)"
            " VALUES (gen_random_uuid(), :h, :c, :v, :a)"
        ),
        {"h": household, "c": category, "v": month, "a": amount},
    )
